#################
### AUTOSTART ###
#################

# system
exec-once = awww-daemon
exec-once = hypridle

# hooks
exec-once = zsh -c "source ~/.config/hypr/hooks/autofetch"
exec-once = zsh -c "source ~/.config/hypr/hooks/wallpaper ~/.config/wallpapers/landscape-infrared-5120x2880-21169.jpg"

# user
exec-once = discord
